apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "kube-gchat.fullname" . }}
  namespace: {{ .Values.application_env }}
spec:
  backendType: systemManager
  dataFrom:
    - /{{.Values.application_env}}/{{include "kube-gchat.fullname" .}}/hangout-hubot.json
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "kube-gchat.fullname" . }}-env
  namespace: {{ .Values.application_env }}
spec:
  backendType: systemManager
  dataFrom:
    - /{{.Values.application_env}}/{{include "kube-gchat.fullname" .}}/env