apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-gchat.fullname" . }}-external-scripts
  labels:
    {{- include "kube-gchat.labels" . | nindent 4 }}
data:
  external-scripts.json: |-
    [
    {{- range .Values.externalScripts }}
      {{ . | quote }},
    {{- end }}
      "hubot-diagnostics",
      "hubot-help",
      "hubot-redis-brain",
      "hubot-rules",
      "hubot-google-images",
      "hubot-google-translate",
      "hubot-pugme",
      "hubot-maps",
      "hubot-shipit"
    ]
