apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-gchat.fullname" . }}
  labels:
    {{- include "kube-gchat.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "kube-gchat.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
